from enum import Enum


class Status(Enum):
    HP_PERCENT = "HP%"
    ATK_PERCENT = "공격력%"
    DEF_PERCENT = "방어력%"
    CRIT_RATE = "치명타 확률%"
    CRIT_DMG = "치명타 피해%"
    ELEMENTAL_MASTERY = "원소 마스터리"
    DEF = "방어력"
    HP = "HP"
    ATK = "공격력"
    ENERGY_RECHARGE = "원소 충전 효율%"
    ANEMO_DAMAGE_BONUS = "바람 원소 피해 보너스%"
    CRYO_DAMAGE_BONUS = "얼음 원소 피해 보너스%"
    DENDRO_DAMAGE_BONUS = "풀 원소 피해 보너스%"
    ELECTRO_DAMAGE_BONUS = "번개 원소 피해 보너스%"
    GEO_DAMAGE_BONUS = "바위 원소 피해 보너스%"
    HYDRO_DAMAGE_BONUS = "물 원소 피해 보너스%"
    PYRO_DAMAGE_BONUS = "불 원소 피해 보너스%"
    PHYSICAL_DAMAGE_BONUS = "물리 피해 보너스%"


class ArtifactName(Enum):
    GLADIATOR_FINALE = "검투사의 피날레"
    WANDERRER_TROUPE = "대지를 유랑하는 악단"
    NOBLESSE_OBLIGE = "옛 왕실의 의식"
    BLOODSTAINED_CHIVALRY = "피에 물든 기사도"
    MAIDEN_BELOVED = "사랑받는 소녀"
    VIRIDESCENT_VENERER = "청록색 그림자"
    ARCHAIC_PETRA = "유구한 반암"
    RETRACING_BOLIDE = "날아 오르는 유성"
    THUNDER_SOOTHER = "뇌명을 평정한 존자"
    THUNDERING_FURY = "번개 같은 분노"
    LAVA_WALKER = "불 위를 걷는 현인"
    CRIMSON_WITCH_OF_FLAMES = "불타오르는 화염의 마녀"
    BLIZZARD_STRAYER = "얼음바람 속에서 길잃은용사"
    HEART_OF_DEPTH = "몰락한 마음"
    TENACITY_OF_THE_MILLELITH = "견고한 천암"
    PALE_FLAME = "창백의 화염"
    SHIMENAWA_REMINISCENCE = "추억의 시메나와"
    EMBLEM_OF_SEVERED_FATE = "절연의 기치"
    HUSK_OF_OPULENT_DREAMS = "풍요로운 꿈의 껍데기"
    OCEAN_HUED_CLAM = "바다에 물든 거대 조개"
    VERMILLION_HEREAFTER = "진사 왕생록"
    ECHOES_OF_AN_OFFERING = "제사의 여운"
    DEEPWOOD_MEMORIES = "숲의 기억"
    GILDED_DREAMS = "도금된 꿈"
    DESERT_PAVILION_CHRONICLE = "모래 위 누각의 역사"
    FLOWER_OF_PARADISE_LOST = "잃어버린 낙원의 꽃"


class Part(Enum):
    FLOWER_OF_LIFE = "생명의 꽃"
    PLUME_OF_DEATH = "죽음의 깃털"
    SANDS_OF_EON = "시간의 모래"
    GOBLET_OF_EONOTHEM = "공간의 성배"
    CIRCLET_OF_LOGOS = "이성의 왕관"
